### PR TITLE
Support for Kohana 3.2

### PR DESCRIPTION
**Pull request by digitaljohn**
The way configs are loaded has changed...

### CODE REVIEW

**Comment by banks** [comment]
I've not used this module or kohana in a long while. I'm sure this fix is correct for the changes however I'm reluctant to pull any code I haven't tested or don't understand though. If you want to take over maintaining this module I'd be more than happy to bless your fork as the master repo.

**Comment by digitaljohn** [comment]
Bless away :)

**Comment by banks** [comment]
I've contacted GitHub support. They can either make your fork the master or you can remove/rename your fork and have this repo transfered to your account. Not totally sure about the pros and cons but I guess making your fork the master would save you re-committing your changes. 

Can you confirm what you'd prefer and I'll reply to support. 

Thanks

**Comment by digitaljohn** [comment]
Sorry for the delay... ask for them to make mine the master please :)

Thanks

**Comment by Yahasana** [comment]
Hi Banks, so I'm curious what you'll using now?

**Comment by banks** [comment]
I'm not :).

I stopped doing freelance work a while ago and worked for companies who are not using Kohana and have other solutions for things like email sending (think commercial distributed messaging services). I'm not saying this is bad, I just am not using this code for any professional or personal projects right now. I'd encourage anyone who does use this to follow the new master repo at digitaljohn/kohana-email as that will hopefully continue to be maintained.

Thanks for the interest :)

**Comment by Yahasana** [comment]
Thanks, haha.

You're a smart guy

**Pull request closed without merging**
